config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contatos
  root 'contatos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
	validates :celular, numericality: true
	validates :celular, presence: true
	validates :nome, presence: true
	validates :nome, uniqueness: true, on: :create
	validates :celular, uniqueness: true, on: :create

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
 	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

 	def self.search(query)
 		where("nome like ?", "%#{query}%")

 		
 	end

 	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /contatos
  # GET /contatos.json
  def index
    if params[:search]
        @contatos = Contato.search(params[:search])
    else
      @contatos = Contato.all
    end
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end 

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :celular, :avatar)
    end
end
2341231

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<%= form_with(model: contato, local: true, multipart: true ) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class=col-sm-6>

  <div class="row">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="row">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="row">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>
  
  
  <div class="avatar">
 <%= form.file_field :avatar %>
  </div>


  <div class="actions">
    <%= form.button "Salvar"%>
  </div>
</div>
  
<% end %>

 

app/views/contatos/edit.html.erb
<h1>Contato <span class="badge badge-pill badge-dark">Editar</span> </h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Show', @contato , class: 'btn btn-info' %> 
<%= link_to 'Back', contatos_path , class: 'btn btn-info'%>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Contatos <span class="badge badge-pill badge-dark">Lista</span> </h1>

<%= form_tag(contatos_path, :method => :get) do %>
<%= text_field_tag 'search', nil, placeholder: 'Buscar contato'%>
<%= submit_tag "Buscar" %>
<% end %>



<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Celular</th>
       <th class= 'text-right'</th>
    </tr>
<br>
  </thead>

  <tbody >
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.celular %></td>
        <td><%= link_to 'Detalhes', contato, class: 'btn btn-info' %>
        <%= link_to 'Editar', edit_contato_path(contato) , class: 'btn btn-info'%>
        <%= link_to 'Excluir', contato_path(contato.id), method: :delete, data: { confirm: 'Você tem certeza?' } , class: 'btn btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Contato', new_contato_path , class: 'btn btn-info'%>

app/views/contatos/new.html.erb
<h1>Contato <span class="badge badge-pill badge-dark">Novo</span> </h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Back', contatos_path , class: 'btn btn-info'%>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos <span class="badge badge-pill badge-dark">Detalhes</span> </h1>
<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @contato.celular %>
</p>

<p>
  <strong>Foto contato:</strong>

</br>

  <%= image_tag @contato.avatar.url(:medium) %>
</p>



<%= link_to 'Edit', edit_contato_path(@contato) , class: 'btn btn-info'%> 
<%= link_to 'Back', contatos_path, class: 'btn btn-info' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" <%= link_to 'AGENDA', contatos_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Home', contatos_path %></a>
      </li>
      <li>  <a class="nav-link"  <%= link_to 'Novo Contato', new_contato_path %> </li>
     
      
    </ul>
  
   
  <% if user_signed_in? %> 
  <span class="text-white bg-dark"> <%= current_user.email %></span>
         <div class="nav justify-content-end" id="navbarsExample03"> 
           <ul class="navbar-nav mr-auto"> 
              <li><a class="nav-link" <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
           </ul>
         </div>
  
  <% else %>
       <div class="nav justify-content-end" id="navbarsExample03">
          <ul class="navbar-nav mr-auto">
              <li><a class="nav-link" <%= link_to 'Cadastrar Usuario', new_user_registration_path %></a></li>
              <li><a class="nav-link" <%= link_to 'Login', new_user_session_path %></a> </li>
             
          </ul>   
       </div>
          
<% end %>
   </div>
</nav>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>